---
title: "data_cleaning"
format: html
editor: visual
---

```{r}
library(readr)
library(tidyverse) ## for readr, dplyr, ggplot2
```

```{r}
env <- read_csv("env.csv")
macros <- read_csv("macros.csv")
master.taxa <- read_csv("master.taxa.csv")
```

## Combining env + macros + master_taxa

```{r}
#| label: data wrangling
#| message: false
#| warning: false
#| 
##calculate the number of each taxon of interest in each sampleID
macro.taxa <- macros |> 
  
  #join taxonomic information 
  left_join(master.taxa) |> 
  
  # Summarize for each sampleID and taxon 
  group_by(sampleID, taxon_group, benthicArea, FFG) |> 
  dplyr::summarise(number = sum(number, na.rm = TRUE)) |> 
  ungroup() |> 
  
  #calculate the density for your taxon for each sampleID
  mutate(density = number/benthicArea)

#join the macros and env data
vis_analysis_data <- left_join(macro.taxa, env) |> 
  
    #remove variables that are not needed
    #(too many zeros or never correlates with much)
     dplyr::select(-nitrate, -alkalinity, 
                   -per_sediment, -per_rock, -per_organic,
                   -mon.max.wTemp, -mon.median.wTemp,
                   -mon.median.turb, -mon.max.turb)
```


```{r}
write.csv(vis_analysis_data, "vis_analysis.csv", row.names = FALSE)
```




